# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from route_events.route.repo import lrs_pb2 as route__events_dot_route_dot_repo_dot_lrs__pb2

GRPC_GENERATED_VERSION = '1.68.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in route_events/route/repo/lrs_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RoadNetworkStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.DownloadAsSHP = channel.unary_unary(
                '/road_network.RoadNetwork/DownloadAsSHP',
                request_serializer=route__events_dot_route_dot_repo_dot_lrs__pb2.DownloadRequests.SerializeToString,
                response_deserializer=route__events_dot_route_dot_repo_dot_lrs__pb2.FilePath.FromString,
                _registered_method=True)
        self.GetByRouteId = channel.unary_unary(
                '/road_network.RoadNetwork/GetByRouteId',
                request_serializer=route__events_dot_route_dot_repo_dot_lrs__pb2.RouteRequests.SerializeToString,
                response_deserializer=route__events_dot_route_dot_repo_dot_lrs__pb2.Routes.FromString,
                _registered_method=True)


class RoadNetworkServicer(object):
    """Missing associated documentation comment in .proto file."""

    def DownloadAsSHP(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetByRouteId(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RoadNetworkServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'DownloadAsSHP': grpc.unary_unary_rpc_method_handler(
                    servicer.DownloadAsSHP,
                    request_deserializer=route__events_dot_route_dot_repo_dot_lrs__pb2.DownloadRequests.FromString,
                    response_serializer=route__events_dot_route_dot_repo_dot_lrs__pb2.FilePath.SerializeToString,
            ),
            'GetByRouteId': grpc.unary_unary_rpc_method_handler(
                    servicer.GetByRouteId,
                    request_deserializer=route__events_dot_route_dot_repo_dot_lrs__pb2.RouteRequests.FromString,
                    response_serializer=route__events_dot_route_dot_repo_dot_lrs__pb2.Routes.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'road_network.RoadNetwork', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('road_network.RoadNetwork', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RoadNetwork(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def DownloadAsSHP(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/road_network.RoadNetwork/DownloadAsSHP',
            route__events_dot_route_dot_repo_dot_lrs__pb2.DownloadRequests.SerializeToString,
            route__events_dot_route_dot_repo_dot_lrs__pb2.FilePath.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetByRouteId(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/road_network.RoadNetwork/GetByRouteId',
            route__events_dot_route_dot_repo_dot_lrs__pb2.RouteRequests.SerializeToString,
            route__events_dot_route_dot_repo_dot_lrs__pb2.Routes.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
