# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: route_events/route/repo/lrs.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'route_events/route/repo/lrs.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!route_events/route/repo/lrs.proto\x12\x0croad_network\"6\n\x10\x44ownloadRequests\x12\x0e\n\x06routes\x18\x01 \x03(\t\x12\x12\n\noutput_shp\x18\x02 \x01(\t\"\x1f\n\rRouteRequests\x12\x0e\n\x06routes\x18\x01 \x03(\t\"\x18\n\x08\x46ilePath\x12\x0c\n\x04path\x18\x01 \x01(\t\"\x19\n\x06Routes\x12\x0f\n\x07geojson\x18\x01 \x01(\t2\x9d\x01\n\x0bRoadNetwork\x12I\n\rDownloadAsSHP\x12\x1e.road_network.DownloadRequests\x1a\x16.road_network.FilePath\"\x00\x12\x43\n\x0cGetByRouteId\x12\x1b.road_network.RouteRequests\x1a\x14.road_network.Routes\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'route_events.route.repo.lrs_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DOWNLOADREQUESTS']._serialized_start=51
  _globals['_DOWNLOADREQUESTS']._serialized_end=105
  _globals['_ROUTEREQUESTS']._serialized_start=107
  _globals['_ROUTEREQUESTS']._serialized_end=138
  _globals['_FILEPATH']._serialized_start=140
  _globals['_FILEPATH']._serialized_end=164
  _globals['_ROUTES']._serialized_start=166
  _globals['_ROUTES']._serialized_end=191
  _globals['_ROADNETWORK']._serialized_start=194
  _globals['_ROADNETWORK']._serialized_end=351
# @@protoc_insertion_point(module_scope)
